//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ingres.Web.Security {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ingres.Web.Security.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user account has been locked out..
        /// </summary>
        internal static string AccountLockedOut {
            get {
                return ResourceManager.GetString("AccountLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Application Id is available. Has an Application been created yet?.
        /// </summary>
        internal static string ApplicationIdNotFound {
            get {
                return ResourceManager.GetString("ApplicationIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application names cannot contain commas..
        /// </summary>
        internal static string ApplicationNamesCannotContainCommas {
            get {
                return ResourceManager.GetString("ApplicationNamesCannotContainCommas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application name is too long..
        /// </summary>
        internal static string ApplicationNameTooLong {
            get {
                return ResourceManager.GetString("ApplicationNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Application was not found in the database..
        /// </summary>
        internal static string ApplicationNotFoundInTheDatabase {
            get {
                return ResourceManager.GetString("ApplicationNotFoundInTheDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A single user should have been deleted..
        /// </summary>
        internal static string ASingleUserShouldHaveBeenDeleted {
            get {
                return ResourceManager.GetString("ASingleUserShouldHaveBeenDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute not recognized &apos;{0}&apos;.
        /// </summary>
        internal static string AttributeNotRecognized {
            get {
                return ResourceManager.GetString("AttributeNotRecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot unencode a hashed password..
        /// </summary>
        internal static string CannotUnencodeAHashedPassword {
            get {
                return ResourceManager.GetString("CannotUnencodeAHashedPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection name &apos;{0}&apos; was not found in the applications configuration or the connection string is empty..
        /// </summary>
        internal static string ConnectionStringNotFound {
            get {
                return ResourceManager.GetString("ConnectionStringNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve the Application Id.
        /// </summary>
        internal static string CouldNotRetrieveTheApplicationId {
            get {
                return ResourceManager.GetString("CouldNotRetrieveTheApplicationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The custom password validation failed..
        /// </summary>
        internal static string CustomPasswordValidationFailed {
            get {
                return ResourceManager.GetString("CustomPasswordValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; does not match the regular expression specified in config file..
        /// </summary>
        internal static string DoesNotMatchRegex {
            get {
                return ResourceManager.GetString("DoesNotMatchRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The array &apos;{0}&apos; should not contain duplicate values..
        /// </summary>
        internal static string DuplicateArrayElement {
            get {
                return ResourceManager.GetString("DuplicateArrayElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$.
        /// </summary>
        internal static string EmailRegex {
            get {
                return ResourceManager.GetString("EmailRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred whilst attempting to create a user..
        /// </summary>
        internal static string ErrorAttemptingToCreateAUser {
            get {
                return ResourceManager.GetString("ErrorAttemptingToCreateAUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred in retrieving data from the data provider in the GetPassword method..
        /// </summary>
        internal static string ErrorInTheGetPasswordMethod {
            get {
                return ResourceManager.GetString("ErrorInTheGetPasswordMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred whilst attempting to rollback a transaction.
        /// </summary>
        internal static string ErrorRollingBackTransaction {
            get {
                return ResourceManager.GetString("ErrorRollingBackTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred whilst trying to update the LastLoginDate..
        /// </summary>
        internal static string ErrorTryingToUpdateTheLastLoginDate {
            get {
                return ResourceManager.GetString("ErrorTryingToUpdateTheLastLoginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update last activity date..
        /// </summary>
        internal static string FailedToUpdateLastActivityDate {
            get {
                return ResourceManager.GetString("FailedToUpdateLastActivityDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update the Membership details..
        /// </summary>
        internal static string FailedToUpdateMembershipDetails {
            get {
                return ResourceManager.GetString("FailedToUpdateMembershipDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update the Last Activity Date.
        /// </summary>
        internal static string FailedToUpdateTheLastActivityDate {
            get {
                return ResourceManager.GetString("FailedToUpdateTheLastActivityDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(\{){0,1}[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}(\}){0,1}$.
        /// </summary>
        internal static string GuidRegex {
            get {
                return ResourceManager.GetString("GuidRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hashed passwords cannot be decoded..
        /// </summary>
        internal static string HashedPasswordsCannotBeDecoded {
            get {
                return ResourceManager.GetString("HashedPasswordsCannotBeDecoded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured settings are invalid: Hashed passwords cannot be retrieved. Either set the password format to different type, or set supportsPasswordRetrieval to false..
        /// </summary>
        internal static string HashedPasswordsCannotBeRetrieved {
            get {
                return ResourceManager.GetString("HashedPasswordsCannotBeRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password answer..
        /// </summary>
        internal static string IncorrectPasswordAnswer {
            get {
                return ResourceManager.GetString("IncorrectPasswordAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Ingres exception occurred. Please check your event log for details..
        /// </summary>
        internal static string IngresExceptionErrorMessage {
            get {
                return ResourceManager.GetString("IngresExceptionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingres Membership Provider.
        /// </summary>
        internal static string IngresMembershipProvider {
            get {
                return ResourceManager.GetString("IngresMembershipProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingres Role Provider.
        /// </summary>
        internal static string IngresRoleProvider {
            get {
                return ResourceManager.GetString("IngresRoleProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The E-mail supplied is invalid..
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password supplied is invalid.  Passwords must conform to the password strength requirements configured for the default provider..
        /// </summary>
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password-answer supplied is invalid..
        /// </summary>
        internal static string InvalidPasswordAnswer {
            get {
                return ResourceManager.GetString("InvalidPasswordAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password-question supplied is invalid.  Note that the current provider configuration requires a valid password question and answer.  As a result, a CreateUser overload that accepts question and answer parameters must also be used..
        /// </summary>
        internal static string InvalidPasswordQuestion {
            get {
                return ResourceManager.GetString("InvalidPasswordQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provider user key supplied is invalid.  It must be of type System.Guid..
        /// </summary>
        internal static string InvalidProviderUserKey {
            get {
                return ResourceManager.GetString("InvalidProviderUserKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user was not found..
        /// </summary>
        internal static string MembershipUserNotFound {
            get {
                return ResourceManager.GetString("MembershipUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minRequiredNonalphanumericCharacters can not be greater than minRequiredPasswordLength..
        /// </summary>
        internal static string MinRequiredNonalphCharGreaterThanMinRequiredPasswordLength {
            get {
                return ResourceManager.GetString("MinRequiredNonalphCharGreaterThanMinRequiredPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one row was affected..
        /// </summary>
        internal static string MoreThanOneRowWasAffected {
            get {
                return ResourceManager.GetString("MoreThanOneRowWasAffected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one row was affected when attempting to change a password..
        /// </summary>
        internal static string MoreThanOneRowWasAffectedWhenAttemptingToChangeAPassword {
            get {
                return ResourceManager.GetString("MoreThanOneRowWasAffectedWhenAttemptingToChangeAPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one user has the specified e-mail address..
        /// </summary>
        internal static string MoreThanOneUserWithEmail {
            get {
                return ResourceManager.GetString("MoreThanOneUserWithEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one user would have been deleted..
        /// </summary>
        internal static string MoreThanOneUserWouldHaveBeenDeleted {
            get {
                return ResourceManager.GetString("MoreThanOneUserWouldHaveBeenDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a valid value for the Application Name..
        /// </summary>
        internal static string MustSpecifyApplicationName {
            get {
                return ResourceManager.GetString("MustSpecifyApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non alpha numeric characters in &apos;{0}&apos; needs to be greater than or equal to &apos;{1}&apos;..
        /// </summary>
        internal static string NeedMoreNonAlphanumericChars {
            get {
                return ResourceManager.GetString("NeedMoreNonAlphanumericChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection information specified in application configuration file..
        /// </summary>
        internal static string NoConnectionInformationSpecifiedInApplicationConfigurationFile {
            get {
                return ResourceManager.GetString("NoConnectionInformationSpecifiedInApplicationConfigurationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The combination of pageIndex and pageSize cannot exceed the maximum value of System.Int32..
        /// </summary>
        internal static string PageIndexAndPageSizeCombinationInvalid {
            get {
                return ResourceManager.GetString("PageIndexAndPageSizeCombinationInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pageIndex must be greater than or equal to zero..
        /// </summary>
        internal static string PageIndexInvalid {
            get {
                return ResourceManager.GetString("PageIndexInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pageSize must be greater than zero..
        /// </summary>
        internal static string PageSizeInvalid {
            get {
                return ResourceManager.GetString("PageSizeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The array parameter &apos;{0}&apos; should not be empty..
        /// </summary>
        internal static string ParameterArrayEmpty {
            get {
                return ResourceManager.GetString("ParameterArrayEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection parameter &apos;{0}&apos; should not be empty..
        /// </summary>
        internal static string ParameterCollectionEmpty {
            get {
                return ResourceManager.GetString("ParameterCollectionEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; must not contain commas..
        /// </summary>
        internal static string ParameterContainsCommas {
            get {
                return ResourceManager.GetString("ParameterContainsCommas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; must not be empty..
        /// </summary>
        internal static string ParameterEmpty {
            get {
                return ResourceManager.GetString("ParameterEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; is too long: it must not exceed {1} chars in length..
        /// </summary>
        internal static string ParameterTooLong {
            get {
                return ResourceManager.GetString("ParameterTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password answer required for password reset..
        /// </summary>
        internal static string PasswordAnswerRequiredForPasswordReset {
            get {
                return ResourceManager.GetString("PasswordAnswerRequiredForPasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password-answer supplied is wrong..
        /// </summary>
        internal static string PasswordAnswerWrong {
            get {
                return ResourceManager.GetString("PasswordAnswerWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password format specified is invalid..
        /// </summary>
        internal static string PasswordFormatInvalid {
            get {
                return ResourceManager.GetString("PasswordFormatInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is stored in a unrecognised format..
        /// </summary>
        internal static string PasswordIsStoredInAUnrecognisedFormat {
            get {
                return ResourceManager.GetString("PasswordIsStoredInAUnrecognisedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password not Reset..
        /// </summary>
        internal static string PasswordNotReset {
            get {
                return ResourceManager.GetString("PasswordNotReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset is not enabled..
        /// </summary>
        internal static string PasswordResetIsNotEnabled {
            get {
                return ResourceManager.GetString("PasswordResetIsNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This provider is not configured to allow password resets. To enable password reset, set enablePasswordReset to &quot;true&quot; in the configuration file..
        /// </summary>
        internal static string PasswordResetNotConfigured {
            get {
                return ResourceManager.GetString("PasswordResetNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Membership Provider has not been configured to support password retrieval..
        /// </summary>
        internal static string PasswordRetrievalNotSupported {
            get {
                return ResourceManager.GetString("PasswordRetrievalNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is too long: it must not exceed 128 chars after encrypting..
        /// </summary>
        internal static string PasswordTooLong {
            get {
                return ResourceManager.GetString("PasswordTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of parameter &apos;{0}&apos; needs to be greater or equal to &apos;{1}&apos;..
        /// </summary>
        internal static string PasswordTooShort {
            get {
                return ResourceManager.GetString("PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider &apos;{0}&apos; was not found..
        /// </summary>
        internal static string ProviderNotFound {
            get {
                return ResourceManager.GetString("ProviderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Provider encountered an unknown error..
        /// </summary>
        internal static string ProviderUnknownError {
            get {
                return ResourceManager.GetString("ProviderUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password canceled due to password validation failure..
        /// </summary>
        internal static string ResetPasswordCanceledDueToPasswordValidationFailure {
            get {
                return ResourceManager.GetString("ResetPasswordCanceledDueToPasswordValidationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The role &apos;{0}&apos; already exists..
        /// </summary>
        internal static string RoleAlreadyExists {
            get {
                return ResourceManager.GetString("RoleAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This role cannot be deleted because there are users present in it..
        /// </summary>
        internal static string RoleNotEmpty {
            get {
                return ResourceManager.GetString("RoleNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The role &apos;{0}&apos; was not found..
        /// </summary>
        internal static string RoleNotFound {
            get {
                return ResourceManager.GetString("RoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied user name was not found..
        /// </summary>
        internal static string SuppliedUserNameWasNotFound {
            get {
                return ResourceManager.GetString("SuppliedUserNameWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied user is locked out..
        /// </summary>
        internal static string TheSuppliedUserIsLockedOut {
            get {
                return ResourceManager.GetString("TheSuppliedUserIsLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied user name is not found..
        /// </summary>
        internal static string TheSuppliedUserNameIsNotFound {
            get {
                return ResourceManager.GetString("TheSuppliedUserNameIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is locked out..
        /// </summary>
        internal static string TheUserIsLockedOut {
            get {
                return ResourceManager.GetString("TheUserIsLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update failure count..
        /// </summary>
        internal static string UnableToUpdateFailureCount {
            get {
                return ResourceManager.GetString("UnableToUpdateFailureCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update failure count and window start..
        /// </summary>
        internal static string UnableToUpdateFailureCountAndWindowStart {
            get {
                return ResourceManager.GetString("UnableToUpdateFailureCountAndWindowStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A unique email is required..
        /// </summary>
        internal static string UniqueEmailRequired {
            get {
                return ResourceManager.GetString("UniqueEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred..
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unkown Ingres Asp Net Provider.
        /// </summary>
        internal static string UnkownIngresAspNetProvider {
            get {
                return ResourceManager.GetString("UnkownIngresAspNetProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported password format..
        /// </summary>
        internal static string UnsupportedPasswordFormat {
            get {
                return ResourceManager.GetString("UnsupportedPasswordFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user &apos;{0}&apos; is already in role &apos;{1}&apos;..
        /// </summary>
        internal static string UserAlreadyInRole {
            get {
                return ResourceManager.GetString("UserAlreadyInRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user &apos;{0}&apos; is already not in role &apos;{1}&apos;..
        /// </summary>
        internal static string UserAlreadyNotInRole {
            get {
                return ResourceManager.GetString("UserAlreadyNotInRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not exist.
        /// </summary>
        internal static string UserDoesNotExist {
            get {
                return ResourceManager.GetString("UserDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A username must be supplied to get a User..
        /// </summary>
        internal static string UsernameMustBeSuppliedToGetAUser {
            get {
                return ResourceManager.GetString("UsernameMustBeSuppliedToGetAUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user was not found in the database..
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user &apos;{0}&apos; was not found..
        /// </summary>
        internal static string UserWasNotFound {
            get {
                return ResourceManager.GetString("UserWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid Application name has not yet been set..
        /// </summary>
        internal static string ValidApplicationNameNotSet {
            get {
                return ResourceManager.GetString("ValidApplicationNameNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be boolean (true or false) for property &apos;{0}&apos;..
        /// </summary>
        internal static string ValueMustBeBoolean {
            get {
                return ResourceManager.GetString("ValueMustBeBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be a non-negative 32-bit integer for property &apos;{0}&apos;..
        /// </summary>
        internal static string ValueMustBeNonNegativeInteger {
            get {
                return ResourceManager.GetString("ValueMustBeNonNegativeInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be a positive 32-bit integer for property &apos;{0}&apos;..
        /// </summary>
        internal static string ValueMustBePositiveInteger {
            get {
                return ResourceManager.GetString("ValueMustBePositiveInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; can not be greater than &apos;{1}&apos;..
        /// </summary>
        internal static string ValueTooBig {
            get {
                return ResourceManager.GetString("ValueTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password supplied is wrong..
        /// </summary>
        internal static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not unlock a user without suplying a valid userName..
        /// </summary>
        internal static string YouCanNotUnlockAUserWithoutSuplyingAValidUserName {
            get {
                return ResourceManager.GetString("YouCanNotUnlockAUserWithoutSuplyingAValidUserName", resourceCulture);
            }
        }
    }
}
